// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaa_XT2vuDA37GO7MSFeYz2bfleWwbAmA',
    appId: '1:506983592383:web:1344b5624dcf1cd24eb10a',
    messagingSenderId: '506983592383',
    projectId: 'login-b0a4f',
    authDomain: 'login-b0a4f.firebaseapp.com',
    storageBucket: 'login-b0a4f.appspot.com',
    measurementId: 'G-5RL67KZCPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1aGsFhpTBWZRNMRtDLL0p4EscIeVpAyc',
    appId: '1:506983592383:android:7079036fe7603d174eb10a',
    messagingSenderId: '506983592383',
    projectId: 'login-b0a4f',
    storageBucket: 'login-b0a4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQv38emM3up-L3JvMNgvq2UV-xst6Mty8',
    appId: '1:506983592383:ios:5026058b2bd506d24eb10a',
    messagingSenderId: '506983592383',
    projectId: 'login-b0a4f',
    storageBucket: 'login-b0a4f.appspot.com',
    iosBundleId: 'com.example.pusoil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaa_XT2vuDA37GO7MSFeYz2bfleWwbAmA',
    appId: '1:506983592383:web:3d69769d5d148d5e4eb10a',
    messagingSenderId: '506983592383',
    projectId: 'login-b0a4f',
    authDomain: 'login-b0a4f.firebaseapp.com',
    storageBucket: 'login-b0a4f.appspot.com',
    measurementId: 'G-0F89NCK34N',
  );
}
